PRIV_DIR=$(MIX_APP_PATH)\priv
NIF_PATH=$(PRIV_DIR)\libfine_test.dll

C_SRC=$(MAKEDIR)\c_src\fine_test
CPPFLAGS=/LD /std:c++17 /W4 /O2 /EHsc
CPPFLAGS=$(CPPFLAGS) /I"$(ERTS_INCLUDE_DIR)" /I"$(FINE_INCLUDE_DIR)"
# We want to eliminate all warnings, so the end user doesn't see any
CPPFLAGS=$(CPPFLAGS) /WX

SOURCES=$(C_SRC)\*.cpp
FINE_HEADERS=$(FINE_INCLUDE_DIR)\*.hpp

build: $(NIF_PATH)

$(NIF_PATH): $(SOURCES) $(FINE_HEADERS)
	@ if not exist "$(PRIV_DIR)" mkdir "$(PRIV_DIR)"
	cl $(CPPFLAGS) $(SOURCES) /Fe"$(NIF_PATH)"
