PRIV_DIR=$(MIX_APP_PATH)\priv
NIF_PATH=$(PRIV_DIR)\libexample.dll

C_SRC=$(MAKEDIR)\c_src
CPPFLAGS=/LD /std:c++17 /W4 /O2 /EHsc
CPPFLAGS=$(CPPFLAGS) /I"$(ERTS_INCLUDE_DIR)" /I"$(FINE_INCLUDE_DIR)"

SOURCES=$(C_SRC)\*.cpp

all: $(NIF_PATH)

$(NIF_PATH): $(SOURCES)
	@ if not exist "$(PRIV_DIR)" mkdir "$(PRIV_DIR)"
	cl $(CPPFLAGS) $(SOURCES) /Fe"$(NIF_PATH)"
