name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - "v*.*"
jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2"
          elixir-version: "1.18.2"
      - run: mix deps.get --check-locked
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - run: mix compile --warnings-as-errors

  test:
    runs-on: ${{ matrix.os.id }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: "Linux", id: "ubuntu-24.04" }
          - { name: "Windows", id: "windows-2022" }
          - { name: "macOS", id: "macos-14" }
        pair:
          - { elixir: "1.15.8", otp: "25.3" }
          - { elixir: "1.18.2", otp: "27.2" }
    env:
      MIX_ENV: test
    name: Test (${{ matrix.os.name }}, ${{ matrix.pair.elixir }}, ${{ matrix.pair.otp }})
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
        if: ${{ !startsWith(matrix.os.id, 'macos') }}
      - run: |
          curl -fsSO https://elixir-lang.org/install.sh
          sh install.sh elixir@${{ matrix.pair.elixir }} otp@${{ matrix.pair.otp }}
          otp_bin=($HOME/.elixir-install/installs/otp/*/bin)
          elixir_bin=($HOME/.elixir-install/installs/elixir/*/bin)
          echo "$otp_bin" >> "$GITHUB_PATH"
          echo "$elixir_bin" >> "$GITHUB_PATH"
        if: ${{ startsWith(matrix.os.id, 'macos') }}
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ startsWith(matrix.os.id, 'windows') }}
      - run: mix deps.get
        working-directory: test
      - run: mix test
        working-directory: test
      - name: Test example/
        run: |
          mix deps.get --check-locked
          mix format --check-formatted
          mix deps.unlock --check-unused
          mix test --warnings-as-errors
        working-directory: example
        if: ${{ !startsWith(matrix.os.id, 'windows') }}
